[package]
name = "notebook2k1"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.147", features = ["derive"] }
toml = "0.5.9"

[dev-dependencies]
indoc = "1.0.7"
insta = "1.21.2"

